version: '3'
services:

 ngnix:
  container_name: nginx
  image: nginx:stable-alpine
  working_dir: /var/www/htlm
  ports: 
   - "80:80"
   - "443:443"
  volumes:
   - wp-files:/var/www/html
  networks:
   - internal
  restart:
   always

networks:
        internal:
                driver: bridge
volumes:
        wp-files:
                driver: local
                driver_opts:
                        type: none
                        device: /home/cdesombr/data/wp-files
                        o: bind


